# Generated by Django 5.0.6 on 2024-05-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mail_mailingsrv_mail_mailings_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_view_client', 'Can view client')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
