# Generated by Django 5.0.6 on 2024-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('can_view_mail', 'Can view mail')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
        migrations.AlterModelOptions(
            name='mailingsrv',
            options={'ordering': ('pk',), 'permissions': [('set_is_activated', 'переключатель метки активности'), ('can_view_mailings', 'Can view mailings')], 'verbose_name': 'параметр рассылки', 'verbose_name_plural': 'параметры рассылок'},
        ),
    ]
